sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KJfw6Z1p2KhbNuqjus1bZanlb3X7dc6IL9iDNkVKbGtq3wyIkhhX+Yr+JjRxzaW3pCxY9uf8wgyeeFsnKfvUXg7O7qxznW9BaBVp4HTSknomnWdShhwwr9SypR6hVyfRNXdehmV2t59vBg8M7sX+O1QsxXu4SnV5GYwFJcp1Ckj+DsjeDW/wnNq+sC5HyfIzGp63/wrcWCCj9Z1T9CxZm2u5cEV9luHekJnRdsuTZfOupceYJY7ZhHTikwN3hhCZLeb96Za5tg+/VWxLAYRAGSyt7SiYLaKcGvkevd2ttPd0ZGIG5Y7tzggCNEhcrtZtylLFQ8fcnOkK6DR/FP7TPrdB5f2gcD0tajz32XkKPjSe00CCzb0+dz16TEUIUWp++iWfZ7ncyMKJ6hHvxmyF6KKHa4rb5duVO17p5IMcy2qYAiCGZgxcB6OSXu9Bff8v1Ucl5Uz7YqJkP3OeFrgHKW1y3hJPpm7xKPUoF4ayWiWAT2h3k3L4DrzCE8easEqo5HcO99/+btbPsAxuX7YrLZOgESOloCCO0gkUaeP4oR0kzECnyITvNfb69wRBiCs3e1URf823+xJGLJCte2ZfIHSpCjDkWtFlZewhgtyF15yRe1Dd6mfv0DogU14GJfH/5KTYP3ebJ1spFmOqGL3NotH55qjNN5HZOL0Ozh452Mc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Boy-Scouts-in-Mexico--Or-On-Guard-with-Uncle-Sam_2191
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy